import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

import { ComingSoon } from '../components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ComingSoon />
    </div>
  )
}

export default Home
